### ISSUE TITLE
Update Malware Warning

### ISSUE THREAD

**Issue by jzs-cs** [CrowdStrike/detection-container#17]
Enhance warning to make it more obvious that this includes live malware and the non-interactive option could run live malware. Add a step to verify Falcon Prevention settings (maybe inlcude a link to the page or docs).

**Comment by shawndwells** [comment]
Live malware removed. Replaced with inert trojan that connects to bogus internal IP 192.168.0.1.

Refer to https://github.com/CrowdStrike/detection-container/pull/20 for details.

Thanks for helping push this along!
